

#######################
## PRUEBAS api/users ##
#######################

### Crear cliente

POST http://localhost:3000/api/users/crear
Content-Type: application/json

{

    "nombre": "Laura",
    "apellidos": "Martínez",
    "direccion": "Padre Mariana, 34",
    "telefono": "630298689",
    "fnacimiento": "1985-01-31",
    "email": "laura@gmail.com",
    "dni": "90073445Z"

}

###


POST http://localhost:3000/api/users/add
Content-Type: application/json

{

"viaje_id":"62b707477f2192220ae95b7d",
"user_id": "62b70438483835a5ac5954ad"

}

###
### Recuperar clientes

###
GET http://localhost:3000/api/users

### Actualizar cliente

###
PUT http://localhost:3000/api/users/62b6ffb9483835a5ac595486
Content-Type: application/json

{
    "email": "pepe@gmail.com"
}

### Borrar cliente

DELETE http://localhost:3000/api/users/62b6ffb9483835a5ac595486


#########################
## PRUEBAS api/hotels ###
#########################

POST http://localhost:3000/api/hotels/crear
Content-Type: application/json

{

    "nombre": "La Casona de MestasSe abre en una ventana nueva",
    "direccion": "Alqueria de Ferrando, s/n, 03749 Denia, España",
    "ciudad": "Asturias",
    "estrellas": 3,
    "descripcion": "La Casona de Mestas, situada en el parque natural de Ponga, dispone de una piscina termal natural ubicada dentro de una cueva. Esta encantadora casa de campo asturiana conduce a unos bellos jardines y dispone de una terraza con magníficas vistas a las montañas y al río Pong",
    "tarifa": 78,
    "imagen": "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/13781486.jpg?k=7adb7afb612b91528ce4b4a59c458fa52c6bb15bb945208656897a2586f13031&o=&hp=1"

}
### Recuperar hoteles

###
GET http://localhost:3000/api/hotels

### Actualizar hotel

###
PUT http://localhost:3000/api/hotels/62b0a9e14e21b00bbdca1b67
Content-Type: application/json

{
    "ciudad": "Menorca"
}

### Borrar hotel

DELETE http://localhost:3000/api/hotels/62b4a6147e235b46d3d83ec7

#########################
## PRUEBAS api/viajes ###
#########################

### Crear un viaje

POST http://localhost:3000/api/viajes/crear
Content-Type: application/json

{   
    "fechaSalida": "2022-09-12",
    "fechaVuelta": "2022-08-25",
    "IDvueloIda": "86442edf",
    "IDvueloVualta": "91942y5r",
    "hotel": "62b0aa674e21b00bbdca1b69"


}
### Recuperar viajes

###
GET http://localhost:3000/api/viajes

### Actualizar viaje

###
PUT http://localhost:3000/api/viajes/62b0ae7ff4cb6827a44d5cc2
Content-Type: application/json

{
    "hotel": "Senator"
}

### Borrar viaje

DELETE http://localhost:3000/api/viajes/62b0b4c7c35cf14d1dde5cbd